[package]
name = "pimon"
version = "0.1.0"
authors = ["Connor Holloway <c.holloway314@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.9.5"
termion = "1.5.5"
pi-hole-api = "0.1.1"
tokio = "0.2.21"